# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    id: "sticker-track"
    binary: sticker-track
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3

dockers:
  - image_templates:
      - "ghcr.io/sticker-track:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    goarch: amd64
    goamd64: v3
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/sticker-track:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/sticker-track:{{ .Version }}"
    image_templates:
      - "ghcr.io/sticker-track:{{ .Version }}-amd64"
      - "ghcr.io/sticker-track:{{ .Version }}-arm64v8"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
